name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup pico-sdk
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        path: ../../raspberrypi/pico-sdk
    - name: log
      run: echo $GITHUB_WORKSPACE && ls -l $GITHUB_WORKSPACE
    - name: init
      run: cd $GITHUB_WORKSPACE/../../raspberrypi/pico-sdk && git submodule update --init
    # - name: make
    #   run: make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
